from src.util.linked_list import ListInterface, ListNode

# with head and tail

class SinglyLinkedList(ListInterface[int]):
    def __init__(self): ...

    def prepend(self, item): ...

    def append(self, item) -> None: ...

    def remove_at(self, idx): ...

    def get(self, idx): ...

    def remove(self, item): ...
