# queue implementation with a linked list
from src.util.linked_list import ListNode


class Queue:
    def __init__(self, length=0): ...

    def enqueue(self, item): ...

    def deque(self): ...

    def peek(self): ...
