# stack implementation with a linked list and with an array
from src.util.linked_list import ListNode


class LinkedListStack:
    def __init__(self, length=0): ...

    def push(self, item): ...

    def pop(self): ...

    def peek(self): ...


# we emulate a primitive array, cuz the python list is a dynamic array
class ArrayStack:
    def __init__(self, length=0, capacity=5): ...

    def push(self, item): ...

    def pop(self): ...

    def peek(self): ...
